Code4SocialGood/c4sg-web

- src/app/app-routing.module.ts
- src/app/auth.config.ts
- src/app/auth.guard.ts
- src/app/auth.role.component.ts
- src/app/auth.service.ts
- src/environments/environment.dev-heroku.ts
- src/environments/environment.ts
This prevents an unauthorized user to directly access a page and brings the user back to the previous page.
> Augments authorization by preventing unauthorized users to directly access a page

- src/app/user/account/user-account.component.html
> Issue#456-Removing Cancel Button

- src/app/organization/common/organization.service.ts
- src/app/organization/list/organization-list.component.ts
If a spec needs to be filled out, I'll be more than happy to do so.
> Resolving Issue #23

- .travis.yml
> update surge deployment url

- src/app/app.component.html
> replace email text with email icon, mailto link

- src/app/app.component.html
> add forum, slackin links to footer

- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
> projectpagination

- src/app/project/common/project.service.ts
- src/app/project/list/project-list.component.ts
To test
1) login as voulnteer and check My project page it will only show list of projects related to that user
2) login as nonprofit and check the same.
> [issue-11] My Project - Customize for volunteer and nonprofit

- src/app/app.component.html
> Issue#159 - Home - Footer - Rearrange

- src/app/app.component.html
- src/app/app.main.scss
> Issue#160 - Home Page - Footer - Fixed social media icons

- src/app/app.module.ts
> Added JsonpModule

- src/app/organization/common/organization.service.ts
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/user/account/user-account.component.html
- src/app/user/account/user-account.component.ts
- src/app/user/common/user.service.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
Addresses #82 and #92 and updates user stories for logo upload and retrieval.
**To test:**
1. Login as nonprofit user: testnonprofituser2@gmail.com / Opensource5social!
2. Navigate to Jane Doe > My Account
3. Upload an image (use attachment below if needed)
4. Navigate to `http://localhost:4200/user/view/5`, avatar should display
5. Navigate to Jane Doe > My Account, avatar should display
> Avatar upload/retrieval

- src/app/project/view/project-view.component.html
> #151 Project Detail Page - Left Panel - Populate Project Data 

- .travis.yml
- package.json
- src/app/auth.guard.ts
- src/app/navscroll.directive.ts
- src/app/organization/create/organization-create.component.ts
- src/app/organization/edit/organization-edit.component.ts
- src/app/project/common/project.service.ts
- src/app/project/common/project.ts
- src/app/project/view/project-view.component.ts
- src/app/user/account/user-account.component.ts
- src/app/user/list/user-list.component.html
- typescript to ~2.2
- codelyzer to ~2.1
- angular/cli to 1.0
> enforce tslint in travis

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
Submitting pull request after fixing code review changes
> Project Detail Page - Right Panel - Populate Opportunities from Nonprofit #152

- src/app/project/view/project-view.component.css
- src/app/project/view/project-view.component.html
> Project Detail Page - Share Button #154

- src/app/app.component.html
> Home Page - Social Media Icons - Add Link #190

- src/app/_services/image-uploader.service.ts
- src/app/organization/create/organization-create.component.html
- src/app/organization/create/organization-create.component.ts
Addresses #85.
To test:
1. Navigate to `/nonprofit/create`
2. Click on the 'upload' button to upload a logo - use the example below if necessary
The logo and its name should now be visible.
3. Fill out the organization name field and click on the 'create' button. The page should navigate to the corresponding detail page - the logo uploaded from step 2 should be visible
> Create Organization - Upload Logo

- src/app/app-routing.module.ts
Reverts Code4SocialGood/c4sg-web#277
> Revert "Remove the auth on user detail page routing"

- src/app/app-routing.module.ts
> "Remove the auth on user detail page routing"

- src/app/organization/edit/organization-edit.component.ts
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/project/common/project.service.ts
- src/app/project/common/project.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/common/user.ts
- src/app/user/edit/user-edit.component.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.ts
Reverts Code4SocialGood/c4sg-web#324
> Revert "Retrieve skills #302"

- src/app/organization/edit/organization-edit.component.ts
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/project/common/project.service.ts
- src/app/project/common/project.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/common/user.ts
- src/app/user/edit/user-edit.component.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.ts
Reverts Code4SocialGood/c4sg-web#342
> Revert "Revert "Retrieve skills #302""

- src/app/_services/validation.service.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/header/header.component.html
- src/app/organization/common/organization.ts
- src/app/organization/edit/organization-edit.component.html
- src/app/organization/edit/organization-edit.component.ts
- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.ts
- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.html
Reverts Code4SocialGood/c4sg-web#341
> Revert "Revert "Edit Page""

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
The following changes done to User Edit Page as per the Issue 325
1) Phone: only display this field if login user is nonprofit user
2) My profile section: only display this section if login user is volunteer user
3) Publish my profile & Notify my for opportunities match my skills: If backend returns 'N', uncheck. If backend returns 'Y', check.
> User Edit page Changes

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/project/list/project-list.component.ts
Kindly review and let me know in case of any changes or if a better approach to solve this issue.
> #300 - Refresh list pages when menu item is clicked to display all items

- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/list/user-list.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
Changes made to Project List and Project View pages to display skills This fix is for issues 338 and 302.
> Opportunities page list view changes

- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
> #298_UserListPage_Display_SocialIcons

- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
> #364_User_View_Social_Links

- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.ts
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
Default Avatar displayed as per issue 308
> Default Avatar added to User/Project/Organization List Pages

- src/app/auth.service.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
> #356 - Project View Page - Attempt to login after clicking on Apply fails

- src/app/project/view/project-view.component.ts
Changes done as per issue #383 .
> Project View Page - Skills displayed from back end in right panel

- src/app/app.module.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.scss
- src/app/project/list/project-list.component.ts
- src/app/skill/scroll-skills.directive.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
- src/app/user/list/user-list.component.ts
Infinite scroll was implemented for skill's field. First it loads 10 skills and then on scroll it adds another 10 and etc.
> Fixes #303 Project/User List Pages: Display skill tags in search panel 

- src/app/organization/list/organization-list.component.ts
changes done to organization list page according to issue #380
> Organization list Category

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
Changes done to Project view screen as per issue #276.
> Project View Deletion Button

- src/app/project/view/project-view.component.html
Changes done as per issue #419
> Change skill tag of right panel in project view page

- src/app/auth.service.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
> #402 - Project View Page - Apply Button - Login before Apply

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
Changes made as mentioned in issue #435.
> Organization deletion button confirmation pop up

- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
User View changes as per issue #452.
> User View Deletion Confirmation Pop Up

- src/app/home/home.component.css
Task 404, changed the line color beneath the Keyword search box on home page
> Task 404 Completed, changed the line color

- package.json
- src/app/about/about.component.css
- src/app/about/about.component.html
- src/app/about/about.component.ts
- src/app/app.module.ts
> #437 - About Us - Switching to google maps

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
- src/app/skill/common/skill.service.ts
Changes done as per issue #434.
> Create button check in project edit page

- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.ts
> Skill Selection check in User and Project Edit page

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.scss
- src/app/user/edit/user-edit.component.scss
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
- src/app/user/view/user-view.component.html
Edited some code on the scss pages quickly, also added classes on html where needed. Don't forget to check the View List page, where I put the `card-avatar` from the div and added it to the image itself.
> Fix for the issue 388. The requested images are now circular.

- package-lock.json
- src/app/auth.service.ts
- src/app/header/header.component.html
**Fix: BranchIssue188**
**1. Issued on being redirected when clicking logout can be fixed by using this inside of the login link:**
`routerLink="#" ` instead of `routerLink=""`
**2. Issue on logging in and hard refresh cannot be fixed since Auth0 requires a redirect to a callbackURL.** 
**3. Issued on hard refresh when loging out can be fixed by: in auth.service, instead of setting the window.location manually, use router:**
```
window.location.href = logoutURL; // Instead of this
this.router.navigate(['/']); // Use this
```
> fix login refresh

- src/app/header/header.component.html
To avoid immediate redirect to homepage when user click in the links
"Log In" or "Log Out".
Partially solves #356.
Solves #188 firt item.
> Avoid immediate redirect to homepage when "Log In" or "Log Out"

- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
- src/app/project/view/project-view.component.ts
- src/assets/applied-bookmarked-sprite.svg
The code for #334 works partially correct now but should be changed when backend task #224 - Rese API - Project - return applied and bookmarked - is done.
Right now for #334 following is done:
- added SVG icons Applied and Bookmarked;
- these icons show up on the Project View page if user is logged in and applies or bookmarks project that haven't been already applied for or bookmarked;
- buttons Apply and Bookmarked grey out if user is logged in and applies or bookmarks project;
Needed to be done (waiting for backend):
- it's planned that these icons will be already on the Project View page if user is logged in and already applied or bookmarked project;
-it's planned that buttons Apply and Bookmarked are greyed out if user is logged in and already applied or bookmarked project;
-it's …
> Volunteer User - Opportunity description screen Apply and Share button actions

- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
> Branch issue500 resolved

- src/app/about/about.component.html
> #437 - Fixing marker pop-up

- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.scss
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.scss
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
> Branch issue495

- src/app/user/list/user-list.component.ts
This PR fixes the issue #463 - user list page pagination. Kindly review and let me know in case of any changes.
> #463 - Fixing pagination on user list page

- src/app/project/list/project-list.component.ts
- src/app/user/list/user-list.component.ts
> Search Keyword remove spaces

- src/app/project/list/project-list.component.ts
- src/app/user/list/user-list.component.ts
Reverts Code4SocialGood/c4sg-web#539
> Revert "Search Keyword remove spaces"

- src/app/project/list/project-list.component.ts
- src/app/user/list/user-list.component.ts
Reverts Code4SocialGood/c4sg-web#543
> "Search Keyword remove spaces""

- src/app/header/header.component.html
- src/app/header/header.component.scss
I added an hidden link element for Project, Volunteers, Organizations and setting routerLink to /project, /user, /organization respectively. 
I use this instead of ngClass because ngClass seems to be expensive. we are using ngClass to handle the classnames for the nav right now and the function isAtHome() is called over 200 times when the page renders. if I use ngClass and condiitonal function for each Project, Volunteers, and Organizations to assign the 'active' class, seems too expensive.
> added icon to sub view level BranchIssue386

- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.ts
Changes done as per issue #567
> Skill set limit

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.scss
Resolved issue 522, Align skill section
> Branch issue522

- src/app/project/view/project-view.component.html
Resolved issue 581 Organization Section ...
> Branch for581

- src/app/_style/app.theme.scss
- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/user/edit/user-edit.component.scss
- src/app/user/view/user-view.component.html
require changes made to BranchIssue 550 since they are under the same component, with 2 additional style on user-edit.component.scss.
note: changed upload image on left panel rendering to be cicular
> Branch issue561

- src/app/organization/list/organization-list.component.ts
- src/app/project/list/project-list.component.ts
- src/app/user/list/user-list.component.ts
Resolved issue 570, scroll top on pagination
> Resolved issue 570

- src/app/organization/list/organization-list.component.ts
- src/app/project/edit/project-edit.component.ts
#577
The request was passing the 'name:string' of the 'input:checkbox' but will now pass the value set in the 'OrganizationListComponent.categories' array as expected by the server.
'Team Project' is not supported by 'Restful service' but the value 'T' will be sent.
> Fix for Organization List Page - Search by CategoryMaster

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/organization/list/organization-list.component.ts
- src/app/project/list/project-list.component.ts
- src/app/user/list/user-list.component.ts
This PR resolves the resolves the issues related to reloading of the page when a link in the header is clicked. Kindly review and let me know in case of any changes
> 515 project list refresh page

- src/app/_style/app.card.scss
- src/app/organization/list/organization-list.component.html
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.scss
- src/app/project/list/project-list.component.html
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
- src/app/user/list/user-list.component.html
> Resolved issue 583

- src/app/user/edit/user-edit.component.html
> Resolved issue 556 updated

- src/app/_style/app.card.scss
> Resolved Issue 601 updated

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.scss
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
Resolved 553. Updated skills section html css
> Resolved Issue 553 updated

- src/app/_style/app.card.scss
- src/app/organization/edit/organization-edit.component.html
- src/app/organization/list/organization-list.component.html
- src/app/organization/view/organization-view.component.html
- src/app/project/edit/project-edit.component.html
- src/app/project/list/project-list.component.html
- src/app/project/view/project-view.component.html
- src/app/user/edit/user-edit.component.html
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
this is branch off changes from Issue 564
> removed background color on list, added shadow to list, edit, view image

- src/app/auth.service.ts
- src/app/project/view/project-view.component.ts
> #602 - Login prompt added when clicked on Bookmark

- src/app/_components/project-card/project-card.component.html
- src/app/_style/app.card.scss
Removed padding to realign the Orgainzation field. Also moved the date to the next line to avoid line breaks in the middle of the date. Removed pipe character [now unneeded].
> Fixes #627

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
- src/app/user/edit/user-edit.component.ts
Replaced spans with actual labels so they work nice and Material-like. Adjusted alignment styling of the second column and the drop-downs because this made them a bit misaligned. Removed some unneeded blank lines in the code.
> #559 Fixed input labels

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
> Resolved issue 622

- src/app/_style/app.theme.scss
> Resolved 551

- src/app/user/edit/user-edit.component.ts
Issue# 571
https://github.com/Code4SocialGood/c4sg-web/issues/571
> redirect user to user home view after successful user edit

- src/app/auth.service.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
This PR displays the user avatar in the nav bar instead of user display name. If the avatar image is unavailable, display default avatar. Kindly review and let me know in case of any changes.
> #157 - Display user avatar in the nav bar after login

- src/app/user/edit/user-edit.component.ts
> Resolved issue 661

- src/app/project/list/project-list.component.html
- src/app/user/edit/user-edit.component.ts
> Branch for667

- src/app/project/list/project-list.component.html
> Resolved issue 667

- src/app/auth.service.ts
> #157 - display avatar - adding some more code

- src/app/_components/project-card/project-card.component.html
- src/app/_components/project-card/project-card.component.ts
- src/app/project/list/project-list.component.html
> Resolved issue 683

- src/app/project/common/project.service.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
> Resolved issue 669

- .vscode/settings.json
- src/app/_services/validation.service.ts
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
- src/app/user/edit/user-edit.component.ts
https://github.com/Code4SocialGood/c4sg-web/issues/557
> My Settings - Validation - Issue 557

- src/app/about/about.component.html
- src/app/about/about.component.ts
- src/app/about/agmMarkerProto.js
- src/app/app.module.ts
- src/tsconfig.app.json
added script to modify agmMarker prototype to enable hover effect
> added script to modify agmMarker prototype to enable hover effect

- src/app/_components/select-skill/skill-select.component.html
- src/app/_components/select-skill/skill-select.component.ts
- src/app/project/edit/project-edit.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
Implemented the recommended changes for issue 672
> Changes required for issue 672

- src/app/header/header.component.html
- src/app/header/header.component.scss
added header nav icon to community when url is /about-us
> Branch issue644

- src/app/about/about.component.ts
edited mouseover event on marker to allow only one active info-window
> BranchIssue707

- src/app/_services/validation.service.ts
- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.scss
- src/app/project/edit/project-edit.component.ts
https://github.com/Code4SocialGood/c4sg-web/issues/694
> Branch issue#694

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
https://github.com/Code4SocialGood/c4sg-web/issues/708
> Branch issue708

- src/app/user/edit/user-edit.component.ts
> Resolved issue 705

- src/app/_style/app.theme.scss
Resolved issue 704. Changed toast and tooltip color
> Resolved issue 704

- src/app/_style/app.theme.scss
> Resolved issue 532

- src/app/project/list/project-list.component.html
> Resolved issue 682

- src/app/_components/project-card/project-card.component.html
- src/app/_components/project-card/project-card.component.scss
Project list page project and organization links are working and green now.
> Fix Issues #376, #533, #643

- src/app/project/common/project.service.ts
- src/app/project/list/project-list.component.html
- src/app/project/list/project-list.component.ts
Changes done as per Issue #635.
> Project List add Job Title Parameters

- src/app/user/common/job-title.ts
- src/app/user/common/user.service.ts
- src/app/user/common/user.ts
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
- src/app/user/view/user-view.component.ts
Resolved user part of the issue 706
> Resolved user part of issue 706

- src/app/_style/app.theme.scss
> Resolved issue 742

- src/app/project/view/project-view.component.ts
> Resolved issue 740

- src/app/about/about.component.html
- src/app/about/about.component.ts
> #714 - Display full country name in google maps

- src/app/project/common/project.service.ts
- src/app/project/list/project-list.component.ts
- src/app/user/common/user.service.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.ts
Changes to pass JobTitle for Search in Project and User List. As per issue #635.
> Changes to User & Project List Search Parameters

- src/app/_style/app.sidebar.scss
- src/app/organization/list/organization-list.component.html
- src/app/project/list/project-list.component.html
- src/app/user/list/user-list.component.html
> Resolved issue 684

- src/app/user/list/user-list.component.html
> Branch issue778

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
> Fix Issue #780

- src/app/organization/view/organization-view.component.scss
- src/app/project/view/project-view.component.scss
- src/app/user/view/user-view.component.scss
Overwrote css in project view, organization view and user view css files.
> Fixed issue 520

- src/app/about/about.component.html
- src/app/about/about.component.scss
- src/app/organization/view/organization-view.component.scss
- src/app/project/view/project-view.component.scss
- src/app/user/view/user-view.component.scss
Created new class for about page main container. Added new divs to maintain map in the center.
> Fixed Issue 619

- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.scss
Overwrote some and changed some css classes.
> Fixed issue 781

- src/app/_style/app.sidebar.scss
- src/app/project/list/project-list.component.html
- src/app/user/list/user-list.component.html
> Resolved issue 779

- src/app/user/edit/user-edit.component.html
> Resolved issue 806

- src/app/app.main.scss
- src/app/project/list/project-list.component.html
> Resolved issue 809

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
> Resolved issue 800

- src/app/project/list/project-list.component.html
> Updated branch 809

- src/app/home/home.component.scss
> Resolved issue 546

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
> Resolved issue 831

- src/app/_style/app.sidebar.scss
- src/app/organization/list/organization-list.component.html
> resolved issue 843

- src/app/auth.service.ts
- src/app/header/header.component.ts
> Resolved issue 848

- src/app/auth.service.ts
- src/app/header/header.component.html
> Updated issue 848

- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
> #668 - Displaying volunteer history in sidebar

- src/index.html
Chat Tawk To. Account testvolunteeruser2@gmail.com / Opensource5social!
> Fixes #641 Online Chat Integration

- src/app/app.component.ts
Commented ngDoCheck on app.component.ts
> Resolved issue 882

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
> Updated 790

- src/app/home/home.component.html
- src/app/home/home.component.scss
This PR removes the slider from the home page. Kindly let me know what other changes do we need.
> Removing slider from the home page

- src/app/organization/edit/organization-edit.component.html
- src/app/organization/edit/organization-edit.component.scss
- src/app/organization/edit/organization-edit.component.ts
- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.scss
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
- src/app/user/edit/user-edit.component.ts
> Image Delete Icons for Project,Organization and User

- src/app/home/home.component.html
- src/app/home/home.component.scss
issue #903 
Moving the slogan text up a bit.
> Move homepage slogan up

- src/app/organization/edit/organization-edit.component.html
- src/app/project/edit/project-edit.component.html
- src/app/user/edit/user-edit.component.html
issue #766 
I used the directive `[maxlength]="number"` on the form inputs listed on the issue to limit the characters according to the requirements.
when the input doesn't have any text in it:
when it exceeds the character limit it prevents the user from typing:
> Add minor validations to some form inputs

- src/app/organization/list/organization-list.component.scss
> Resolved issue 914

- src/app/auth.service.ts
> Resolved issue 906

- src/app/user/edit/user-edit.component.html
> Resolved issue 912

- src/app/home/home.component.scss
issue #903 
A little fix to the previous commit
> Move a little bit to the bottom

- src/app/home/home.component.scss
issue #903 
Moving the input field down a bit
> Move the input field down

- src/app/auth.service.ts
> Resolved issue 915

- src/app/_components/shared-btn/shared-btn.component.scss
- src/app/project/view/project-view.component.scss
- src/app/user/view/user-view.component.scss
issue #945, issue #938 and issue #936
> minor change in css element

- src/app/_components/feedback-btn/feedback-btn.component.html
- src/app/_components/feedback-btn/feedback-btn.component.scss
- src/app/_components/feedback-btn/feedback-btn.component.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/index.html
Discourse doesn't have a feature now to allow a user to post as anonymous user, without login. 
The issue was raised here  [https://meta.discourse.org/t/allow-unregistered-users-to-post-as-anonymous/50866/5](url)  but  the co-founder at the end of the discussion said "It is not on our roadmap at the current time."
> Fixes #506 Add Feedback Feature

- src/app/_services/form-constants.service.ts
- src/app/organization/edit/organization-edit.component.ts
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.ts
Changes done as per issue #562.
> Image Size Validation

- src/app/organization/edit/organization-edit.component.ts
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.ts
Changes done as per issue #562. To change error message on console to toast.
> Image Size Validation Changes

- src/app/project/list/project-list.component.scss
I added a little bit of css to the list elements so they could be evenly destributed
> Fix skills section distribution

- src/app/user/edit/user-edit.component.html
Included additional criteria in ngIf
> Fixed issue 979

- src/app/_components/project-card-small/project-card-small.component.html
- src/app/_components/project-card-small/project-card-small.component.scss
- src/app/_components/project-card-small/project-card-small.component.ts
- src/app/app.module.ts
- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.scss
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
Moved the small project list to a module to be consistent throughout the app. Added conditional logic when the user/org has no projects.
> Fix Issue #947 and #980

- src/app/_style/app.theme.scss
- src/app/_style/variables.scss
issue #976, adding a toast orange color, and applying it to modals
> Change modal colors

- src/app/project/view/project-view.component.html
> Minor fix in label alignment

- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.component.ts
issue #968 
Added a Call to Action button to the homepage
> Add CTA Register button

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.scss
Changes done as per issue #927.
> Organization view right col changes

- src/app/user/view/user-view.component.html
Added contional logic to render the border when there are 0 projects on for a user.
> Fixes Issue #980

- src/app/organization/view/organization-view.component.html
Changes done for issue #927. To left align text after the icons.
> Organization view right col icon text alignment

- src/app/home/home.component.html
- src/app/home/home.component.scss
> Resolved issue 1011

- src/app/_components/project-card/project-card.component.html
> Resolved 1012 IE issue

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
- src/app/user/view/user-view.component.ts
> Making View Page Consistent

- src/app/_components/project-card-small/project-card-small.component.ts
- src/app/_components/user-avatar-small/user-avatar-small.component.html
- src/app/_components/user-avatar-small/user-avatar-small.component.ts
- src/app/_components/user-avatar/user-avatar.component.html
- src/app/_components/user-avatar/user-avatar.component.scss
- src/app/_components/user-avatar/user-avatar.component.ts
- src/app/app.module.ts
- src/app/organization/view/organization-view.component.html
- src/app/user/list/user-list.component.html
- src/app/user/view/user-view.component.html
Volunteer users without an avatar set will have their initials in a colorful circle. (See important note on ticket #993)
> Fixed issue #993

- src/app/_components/project-card/project-card.component.html
- src/app/project/view/project-view.component.html
- src/index.html
- src/polyfills.ts
> Resolved issue 603

- src/app/_components/project-card/project-card.component.html
- src/app/_components/project-card/project-card.component.scss
- src/polyfills.ts
> Resolved issue 999

- src/app/_components/project-card/project-card.component.scss
- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
> Resolved issue 1042

- src/app/organization/edit/organization-edit.component.ts
> Resolved issue 1030

- src/app/user/view/user-view.component.html
> Resolved issue 1041

- src/app/app.component.html
> Remove "beta test" image

- src/app/organization/edit/organization-edit.component.html
> Resolved 1058 part 1

- src/app/project/edit/project-edit.component.html
> Resolved issue 1058

- src/app/home/home.component.html
- src/app/home/home.component.scss
> add github repo call to action

- src/app/home/home.component.html
- src/app/organization/edit/organization-edit.component.ts
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
> fix a problem with form labels

- src/app/project/list/project-list.component.html
- src/app/user/list/user-list.component.html
> Resolved issue 1061

- src/app/project/view/project-view.component.html
> Resolved issue 975

- src/app/app.component.html
- src/app/app.component.scss
> add text to footer

- src/app/user/view/user-view.component.html
> resolved issue 932

- src/app/home/home.component.html
resolved issue 1071: Disable mouse wheel scrolling on the map
> Resolved issue 1071

- src/app/home/home.component.scss
> Resolved issue 1060

- src/app/app-routing.module.ts
- src/app/project/edit/project-edit-resolve-jobtitles.ts
- src/app/project/edit/project-edit.component.ts
- src/app/user/common/user.service.ts
> Resolved issue 913

- src/app/user/common/user.service.ts
> Resolved issue 1031

- src/app/_style/app.materialize.scss
- src/app/user/common/user.service.ts
> Branch issue663

- src/app/_components/user-avatar/user-avatar.component.scss
> make avatars round and line them up with the rest

- src/app/auth.service.ts
- src/app/user/edit/user-edit.component.ts
resolved and updated branch for 1009
> Resolved issue 1009 updated

- src/app/home/home.component.ts
> Resolved issue 1105

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
> Resolved issue 1116

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
> Resolved Issue #1120 align projects/organization

- src/app/_style/variables.scss
> Resolved issue 1132

- src/app/home/home.component.html
- src/app/home/home.component.scss
This PR fixes issue #1129. Kindly review and let me know in case of any changes.
> Home page redesign - Featured projects

- src/app/_style/app.theme.scss
> Resolved issue#1152_Country_Label_Dropdown

- src/app/home/home.component.scss
This PR resolves issues #1148 and #1133. Kindly review and let me know in case of any changes.
> #1148 and #1133 - Changed home page cover image and removed the gap

- src/app/appreciations/appreciations.component.scss
- src/app/consultants/consultants.component.html
- src/app/consultants/consultants.component.scss
- src/app/partners/partners.component.html
- src/app/partners/partners.component.scss
> Resolved issue #1143 Pages Under Community

- src/app/header/header.component.scss
> Resolved issue #1131 Menu Items Wrapped

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
> Updated issue 1116

- src/app/_components/user-avatar/user-avatar.component.scss
> Resolved #1119_Volunteer_Avatar_Overlap

- src/app/user/edit/user-edit.component.html
> #1145 issue fix

- src/app/user/view/user-view.component.html
> Resolved issue 1113

- src/app/user/list/user-list.component.html
> Resolved issue 1147

- src/app/organization/view/organization-view.component.html
> Resolved issue 1151

- src/app/project/edit/project-edit.component.ts
> Resolved issue 1170

- src/app/home/home.component.html
This PR resolves issue #1157. We added a "container" class to the featured projects div to mimic the edge margins of the volunteer/organization section.
> Resolved issue 1157

- src/app/_style/app.card.scss
> Resolved issue #1118_Same_Avatar_Size

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
> Resolved issue 1140

- src/app/_style/app.card.scss
> Resolved issue #1182 Volunteers_Image_Align

- src/app/_services/form-constants.service.ts
- src/app/organization/list/organization-list.component.ts
- src/app/organization/view/organization-view.component.ts
> Resolved issue #1192 Organization Category

- src/app/user/edit/user-edit.component.ts
> Resolved issue 1178

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/index.html
Resolved issue 1173, Home page responsive design
> Resolved issue 1173

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/index.html
Reverts Code4SocialGood/c4sg-web#1207
> Revert "Resolved issue 1173"

- src/app/_style/app.theme.scss
- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.scss
1. Adding information icon
2. Changing tooltip color
> Add information icon: closes #1171

- src/app/user/edit/user-edit.component.html
- src/app/user/edit/user-edit.component.ts
> Updated issue 1178

- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
> Resolved issue 1179

- src/app/home/home.component.html
- src/app/home/home.component.scss
Reverts Code4SocialGood/c4sg-web#1211
> Revert "Update branch 1173"

- src/app/app.component.html
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
- src/app/footer/footer.component.ts
- src/app/header/header.component.html
Resolved issue 1215, updated footer
> Resolved issue 1215

- src/app/header/header.component.html
- src/app/header/header.component.scss
> Resolved issue #1138 Login/Signup_Button

- src/app/user/edit/user-edit.component.ts
Resolved avatar and checkbox issues for the new user
> Resolved avatar and checkbox issues for the new user

- src/app/user/view/user-view.component.html
> Resolved issue 1195

- src/app/project/view/project-view.component.html
> Branch issue974

- src/app/home/home.component.html
- src/app/home/home.component.ts
> Branch issue1106

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
When clicked, the added button will move the user to the previous location in their browser's history. The button is currently placed awkwardly on the view and needs to be adjusted with CSS.
> "Back to Search Result" Button Added

- src/app/_components/project-card/project-card.component.html
- src/app/organization/list/organization-list.component.html
- src/app/user/list/user-list.component.html
> Resolved issue 1196

- src/app/project/view/project-view.component.html
> Resolved issue 1115

- src/app/_style/app.content.scss
- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/user/view/user-view.component.html
> Resolved issue 1197

- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.component.ts
- src/app/project/common/project.service.ts
> Resolved issue 1107

- .gitignore
- src/app/home/home.component.html
- src/app/home/home.component.scss
Solves overlapping problem on the home page
> closes 1241

- src/app/_components/user-avatar-header/user-avatar-header.component.html
- src/app/_components/user-avatar-header/user-avatar-header.component.ts
- src/app/_components/user-avatar/user-avatar.component.scss
- src/app/app.module.ts
- src/app/auth.service.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
If there is an avatar URL set and it cannot load, the default avatar image will load instead.
> Fix Issue #1038 Changed default avatar to be shown as user's initials in a circle.

- src/app/home/home.component.ts
> Resolved issue 1265

- src/app/_style/app.theme.scss
> Resolved issue 1256

- src/app/home/home.component.html
- src/app/home/home.component.scss
> Resolved issue 1262

- src/app/home/home.component.html
- src/app/home/home.component.scss
Updated issue 1262 as per comments
> Updated issue 1262 as per comments

- src/app/home/home.component.html
- src/app/home/home.component.scss
> Updated PR for 1262

- src/app/home/home.component.html
issue #1106 Please review and merge this code.
> merge conflict corrected

- src/app/_style/variables.scss
- src/app/home/home.component.scss
This PR is our first attempt to contribute to an open source project. Apologies ahead of time for any first-timer mistakes.
We added teal color as $tertiary-bg-color in variables.scss and replaced $secondary-color with $tertiary-bg-color in .divStats styling.
> Home Page - Map - Statistics - Color #1273 -PR

- src/app/user/edit/user-edit.component.html
We commented out the slack text field in profile settings page.
> Remove Slack Field #1251 - PR

- src/app/_components/project-card/project-card.component.html
- src/app/_components/project-card/project-card.component.scss
- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.scss
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
Added text-overflow class to blocks of text to apply text styling. removed slice function and hard coded "..." to create a dynamic loading of ellipsis.
Added .text-overflow styling for blocks of text to end them after 3 lines and add an ellipsis to indicate further text
> Display description section for Project/Volunteer/Organization page #1242 - PR

- src/app/_style/variables.scss
- src/app/home/home.component.scss
Reverts Code4SocialGood/c4sg-web#1281
Change back to orange color
> Revert "Home Page - Map - Statistics - Color #1273 -PR" 

- src/app/user/edit/user-edit.component.ts
> Resolved issue 1204

- src/app/home/home.component.html
- src/app/home/home.component.scss
> added Materialize CSS styled cards for the featured project section.

- src/app/_style/app.content.scss
- src/app/_style/app.theme.scss
https://github.com/Code4SocialGood/c4sg-web/issues/1300
> #1300 css issue

- src/app/consultants/consultants.component.html
- src/app/consultants/consultants.component.scss
- src/app/consultants/consultants.component.ts
> Resolved issue 1146

- src/app/_services/validation.service.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/consultants/consultants.component.scss
- src/app/contact/contact.component.html
- src/app/contact/contact.component.scss
- src/app/contact/contact.component.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
- src/app/user/view/user-view.component.html
> Updated footer, & Implemented "Contact" component

- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.component.ts
> Resolved 1296

- src/app/home/home.component.html
> Resolved issue 1292

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
> Resolved 1213

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/stories/stories.component.html
- src/app/stories/stories.component.ts
> Resolved issue 1290

- src/app/_style/app.theme.scss
- src/app/organization/list/organization-list.component.html
- src/app/organization/view/organization-view.component.html
- src/app/project/list/project-list.component.html
- src/app/project/view/project-view.component.html
- src/app/user/list/user-list.component.html
- src/app/user/view/user-view.component.html
> Back button style

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/stories/stories.component.html
- src/app/stories/stories.component.ts
Reverts Code4SocialGood/c4sg-web#1318
> Revert "Revert "Resolved issue 1290""

- src/app/home/home.component.html
Update branch for issue 1292 as per comments
> Updated branch for 1292

- src/app/home/home.component.html
- src/app/home/home.component.scss
Updated branch for 1296 as per comments
> Updated branch for 1296

- src/app/organization/list/organization-list.component.scss
- src/app/project/list/project-list.component.scss
- src/app/user/list/user-list.component.scss
Resolved List pages styling, made it consistent
> Resolved List pages styling, made it consistent

- src/app/auth.service.ts
- log in as social user, confirm that you can apply to a project.
- log in with email, confirm that you can apply to a project.
> refactor: replace length check with jwt decode check

- src/app/consultants/consultants.component.html
> Resolved issue 1333

- src/app/partners/partners.component.html
> Resolved issue 1334

- src/app/_style/app.fonts.scss
- src/app/_style/app.theme.scss
Edited theme.scss & fonts.scss
> Issue #1024

- src/app/about/about.component.html
- src/app/about/about.component.scss
> Updated 1297 as per comments

- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
> Resolved 1327

- src/app/about/about.component.html
- src/app/about/about.component.scss
> Updated 1297

- src/app/app.module.ts
- src/app/application/common/application.service.ts
- src/app/application/common/applicationProject.ts
- src/app/application/view/application-project-view.component.html
- src/app/application/view/application-project-view.component.scss
- src/app/application/view/application-project-view.component.ts
- src/app/application/view/application-view.component.ts
- src/app/project/common/project.service.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
This PR is related to the back end PR #371
> Chnages for Apply for Project - Volunteer Detail Page - Organization User View

- src/app/footer/footer.component.scss
- src/app/stories/stories.component.scss
Reverts Code4SocialGood/c4sg-web#1421
> Revert "#1399, move coming soon to the middle, move footer to the bottom of t…"

- src/app/about/about.component.html
- src/app/about/about.component.scss
Add bold words under images
Make the text left aligned.
changed src/app/about/about.component.html and src/app/about/about.component.scss
Please accept pull request
> Resolved Issue 1425 and made the page responsive

- npm-debug.log.50517939
- src/app/_style/app.theme.scss
- src/app/home/home.component.html
- src/app/project/view/project-view.component.html
> Projectpanel

- README.md
- src/app/home/home.component.scss
This README file is for C4SG-web
> 1414 corrected readmec4 sg services

- src/app/about/about.component.scss
issue solved margin-top reduced
> AboutUs page margin-top reduced

- src/app/footer/footer.component.scss
Added margine-bottom to the footer
> Added space to bottom footer

- src/app/footer/footer.component.scss
Reverts Code4SocialGood/c4sg-web#1449
> Revert "Added space to bottom footer"

- src/app/user/view/user-view.component.html
> 1453 - Apply for project - Fixing the application section visibility

- src/app/home/home.component.html
- src/app/home/home.component.scss
> 1355- Home Page - Map - Removing the user profile image on the map pop-up

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/help/help.component.html
- src/app/help/help.component.ts
This is the basic UI for the page. Kindly let me know the changes required.
> Issue 1216 - Introducing help page

- package.json
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/organization/common/organization.service.ts
- Add Total Countries involved
- Update Typescript version
Closes #1348
> Add Country statistics

- src/app/contact/contact.component.html
- src/app/contact/contact.component.scss
>added mail icon.
>added mailto link and changed text color.
>added  media queries for small and medium devices.
laptop view
ipad
mobile view
> Contact us page UI Enhancements done and the page is responsive

- src/app/appreciations/appreciations.component.html
- src/app/appreciations/appreciations.component.scss
#1461 Please review the change. Thanks.
> fix for avatar in Heroes page added

- src/app/home/home.component.html
- src/app/home/home.component.scss
changed the css for cards so that it has a min-height to override the max-height of generic card class 200px.
> improve cards

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.ts
This PR adds side navigation for smaller screens. Some changes are pending which will be taken care by another developer.
> PR for Issue 1356 - Home Page - Responsive Menu

- src/app/home/home.component.html
Changes in the map to remove details from the marker pop-up. Kindly review and let me know in case of any changes.
> PR to resolve issue 1466-Home Page - Map - Organization and Volunteer 

- src/app/appreciations/appreciations.component.html
- src/app/appreciations/appreciations.component.scss
#1487 Please review the changes. Thanks.
> issue #1487 fixed

- src/app/appreciations/appreciations.component.scss
- src/app/partners/partners.component.html
- src/app/partners/partners.component.scss
#1492 Please review the changes. Thanks.
> changes made to give same look and feel as Consultants page

- src/app/footer/footer.component.scss
> -Resolved issue #1437

- src/app/auth.service.ts
- src/app/header/header.component.html
#1498 issue with the drop down fixed.
> changes for the header dropdown and it's default avatar added

- src/app/header/header.component.html
Fixing the drop down issue on the home page. Kindly review and let me know in case of any changes
> PR to ressolve issue 1498 - Home Page Drop Down

- src/app/footer/footer.component.html
> Resolved Issue-1513

- src/app/_services/form-constants.service.ts
- src/app/organization/list/organization-list.component.ts
> Social Enterprise category added

- src/app/appreciations/appreciations.component.html
- src/app/appreciations/appreciations.component.scss
Changes are made as per the issue #1491. Please review.
> avatar sizing fixed and the skill tags removed

- src/app/home/home.component.ts
> issue 1537 fixed

- src/app/header/header.component.scss
- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.component.ts
Issue #1554 #1555 #1556 #1557 are fixed. Please review. Thanks.
> Video home

- src/app/home/home.component.html
- src/app/home/home.component.scss
Code for the responsive behavior of map-statistics. Kindly let me know in case of any changes
> PR for the issue #1358 - Responsive Design - Home Page - Statistic on google map is trimmed

- src/app/contact/contact.component.html
> contactus page rephrase done

- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/stories/stories.component.html
- src/app/stories/stories.component.ts
> #1510 Signup Button Our Stories

- src/app/home/home.component.html
- src/app/home/home.component.scss
See More button is center aligned now
> Issue 1523

- src/app/home/home.component.html
- src/app/home/home.component.scss
Fixing the dynamic text for responsive behavior. Kindly review and let me know in case of any changes.
> PR to fix issue 1357 - Responsive Design - Home Page - Dynamic text is overlapping

- src/app/home/home.component.html
- src/app/home/home.component.scss
> PR to fix issue 1384 - Home Page - Map Statistics - Mouse Over

- src/app/organization/view/organization-view.component.ts
issue #1535 is fixed. Please review. Thanks.
> Social Enterprise category is added to the Organization view page

- docs/fontend-development.md
The only difference from the original file is that i've removed the table of contents (to be consistent with the setup.md file and because the file is so short that a TOC is not needed now)
> Conversion to markdown

- docs/backend-development.md
Other minor changes:
* "2.4 Visualization" changed to "1.4 Visualization"
* Removed colon at the end of some of the headers
> Conversion to markdown (backend development)

- docs/github.md
Changed from the table format to instead using lists
> Converted to markdown (github document)

- src/app/about/about.component.html
- src/app/about/about.component.scss
> About us page refactor completed.
>styles added
> About us page refactor done

- src/app/appreciations/appreciations.component.html
- src/app/appreciations/appreciations.component.scss
- src/app/appreciations/footer.component.html
Modified footer to reflect appropriate change as well.
> Fix #1613: Heroes Page - Change text(only) content

- src/app/header/header.component.html
- src/app/header/header.component.ts
> PR to fix issue 1638 - Prod Issue - Extra Page Refreshed after prod release

- src/app/partners/partners.component.html
- src/app/partners/partners.component.scss
Kindly review and let me know in case of any changes. Thanks!
> PR to fix issue 1634 - Partners Page

- src/app/appreciations/appreciations.component.html
- src/app/stories/stories.component.scss
Make the size of organization logos consistent by changing one CSS file.
> PR to fix #1591 organization logos consistent on story page

- src/app/about/about.component.html
- src/app/about/about.component.scss
>styles added 
>card padding  adjusted
> about us page-card top gap reduced

- src/app/about/about.component.html
> added container class adjust the content width 80%
> Aboutus page container width changed to 80%

- .gitignore
- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/project/common/input.formatter.directive.ts
- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.html
Fix for issue #1194 - Added required directive to force lowercase and prevent the use of 'space' (replaced by '-' on the fly) when a user enters text in Skills textbox. Also added info icon and tooltip text. 
This is my first ever issue fix on an OS project - please feel free to provide your feedback. 
Thanks.
> #1194 - Enter Skill Tag - enforce formatting

- .gitignore
- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/project/common/input.formatter.directive.ts
- src/app/project/edit/project-edit.component.html
- src/app/project/edit/project-edit.component.ts
- src/app/user/edit/user-edit.component.html
Reverts Code4SocialGood/c4sg-web#1656
> Revert "Revert "#1194 - Enter Skill Tag - enforce formatting""

- src/app/appreciations/appreciations.component.scss
Hello everyone! 
I'm new to open-source code contribution. 
About this issue,
I changed a few lines in `.../c4sg-web/src/app/appreciations/component.scss`.
So, i added in `.thanks{` -> `font-family: $main-font; font-size:1.3rem; font-weight:bold; color:#4B4B4C` (this $main-font refers to a variable in `.../app/_style/app.fonts.scss`) and deleted a line in `h2{` containing `font-family:Raleway;`
Hope it resolves the open issue.
Greetings, 
VitorDiass
> Top Volunteers Page - font modified  

- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
Fixing footer overlap issue. Kindly review and let me know in case of any changes.
> PR to fix issue 1582 - Responsive Design - Footer is overlapping

- src/app/home/home.component.scss
Adding underline to map statistics on hover
> PR to fix issue 1599 - Home - Map Statistics - Mouse Over

- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
> completed issue 1426

- src/app/home/home.component.html
- src/app/home/home.component.scss
Hope this fix the issue:
Result:
In the process of solving this, i found out that if we resize the window the buttons design are not responsive. I guess this is another issue that needs to be fixed.
> Home Page - Buttons

- src/app/_components/project-card-small/project-card-small.component.html
- src/app/_components/project-card/project-card.component.html
- src/app/app.module.ts
- src/app/project/common/project-image.component.ts
- src/app/project/common/project.ts
- src/app/project/view/project-view.component.html
I botched the first attempt, so this will hopefully be better. I decided to go with a new component to decide which image URL to use, rather than pepper existing component templates with more `*ngIf`.
> use org logo if no project image exists (#1295)

- src/app/home/home.component.html
There is a lot of commented code in `home.component.html`. Should it be cleaned up? If so, should it be part of this PR?
> use `my-project-image` to display project images on home page (#1705)

- package-lock.json
- src/app/_style/app.content.scss
- src/app/organization/view/organization-view.component.html
- src/app/user/view/user-view.component.html
> Aligns Back to Search Button with content

- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/user/view/user-view.component.html
> Standardizes gap between buttons and text

- src/app/_components/shared-btn/shared-btn.component.scss
Update shared-btn.component.scss
1. Changed background of share button as shown in wireframe.
2. Updated background to be green with white text when moused over.  
Additionally updated corresponding social media link to reflect above changes. 
3. Removed unrelated commits in PR.
Apologies!!!
Thank you.
> FIX ISSUE #1714: SHARE BUTTON

- docs/setting-up-a-tech-project.md
about the project manager role and volunteer commitment
> Expanded info

- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.ts
- src/app/user/list/user-list.component.ts
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.ts
Please review. Thanks.
Applicants from Project View Page ...
> issue #1713 fixed

- src/app/partners/partners.component.html
- src/app/partners/partners.component.scss
Hi I made some changes (updated the titles and added descriptions) to the partners page that should hopefully resolve issue #1661 
Thanks
> Partners Page - Change text content #1661 Issue

- src/app/home/home.component.scss
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.scss
This pull request addresses issue #1723 to address the See More button not working on iPhone 6 and other mobile views.
A css property of `width: 50%` was added to home.component.scss in the media query at 650px.
Before: 
After:
> See More Button Width on Home Page - Fixes Issue #1723

- src/app/organization/view/organization-view.component.html
- src/app/organization/view/organization-view.component.scss
- src/app/project/view/project-view.component.html
- src/app/project/view/project-view.component.scss
- src/app/user/view/user-view.component.html
- src/app/user/view/user-view.component.scss
issue #1713 button is removed. Please review. Thanks.
> removed the button

- src/app/_components/shared-btn/shared-btn.component.scss
- src/app/home/home.component.html
- src/app/project/common/project-image.component.scss
- src/app/project/common/project-image.component.ts
This addresses issue #1724 button overlapping; we added a media query at 670px to fix the issue.
Before:
After:
> Issue 1724

- src/app/_components/project-card-small/project-card-small.component.html
- src/app/_components/shared-btn/shared-btn.component.html
- src/app/application/view/application-view.component.html
- src/app/organization/view/organization-view.component.html
- src/app/project/view/project-view.component.html
- src/app/user/view/user-view.component.html
Share button toggle action is set to vertical for mobile devices.
issue #1360 is fixed. Please review. Thanks.
> Project detail panel

- src/app/home/home.component.html
- src/app/home/home.component.scss
- src/app/home/home.component.ts
"IT DOESN'T MATTER IF YOU" has been changed to "JOIN US AND," the selectors have been updated and a "!" has been added to the end of each, and a space has been added before and the font size of "GET STARTED!" was made smaller.
> Issue #1747 Fix

- src/app/about/about.component.html
- src/app/about/about.component.scss
- src/app/about/about.component.ts
>changed look and feel-about us page
> issue solved #1761 about us page

- src/app/_style/app.theme.scss
> added space below page-title-center and above footer

- src/app/_style/app.theme.scss
Reverts Code4SocialGood/c4sg-web#1774
> Revert "added space below page-title-center and above footer"

- src/app/_style/app.theme.scss
Reverts Code4SocialGood/c4sg-web#1775
> Revert "Revert "added space below page-title-center and above footer""

- src/app/_style/app.theme.scss
- src/app/partners/partners.component.html
> fixed previous changes to correct issue created by my fix

- src/app/_components/project-card/project-card.component.html
- src/app/_components/project-card/project-card.component.scss
- src/app/organization/list/organization-list.component.html
- src/app/organization/list/organization-list.component.scss
This PR addresses the issue #1745. The code has been changed to limit the project name and organization name to one line. Kindly let me know in case of any changes.
> PR for the issue 1745 - Project/Organization List Page - Display one line of text only

- src/app/footer/footer.component.html
- src/app/help/help.component.html
- src/app/help/help.component.scss
> Changethelookandfeel help1762

- src/app/project/view/project-view.component.html
Closed Project - Disable Apply Button #1770
> Closed Project - Disable Apply Button

- src/app/_style/app.theme.scss
- src/app/partners/partners.component.html
Removed the space as requested in #1777. Hopefully it is not a problem that I took this away from @rpirritano.
I'm a first time contributor (to any open-source project) and thought this was an easy place to start.
I also took a look at the previously mentioned problems #1774 and #1763 and changed the way this was implemented for some code optimisation.
> Removed the space on home page and code optimisation partners page

- src/app/_style/app.card.scss
- src/app/user/common/user.ts
- src/app/user/list/user-list.component.html
- src/app/user/list/user-list.component.ts
> Display number of volunteer projects in list view

- src/app/home/home.component.html
Hi!
A small fix to remove the https warning due to mixed content.
> Fix https warning

- package.json
- src/app/_services/email.service.ts
- src/app/_services/extfilehandler.service.ts
- src/app/_services/image-display.service.ts
- src/app/_services/image-uploader.service.ts
- src/app/about/common/developer.service.ts
- src/app/app.module.ts
- src/app/application/common/application.service.ts
- src/app/auth.service.ts
- src/app/home/home.component.ts
- src/app/organization/common/organization.service.spec.ts
- src/app/organization/common/organization.service.ts
- src/app/organization/edit/organization-edit.component.ts
- src/app/organization/view/organization-view.component.ts
- src/app/project/common/project.service.ts
- src/app/project/edit/project-edit.component.ts
- src/app/project/list/my-projects-nonprofit.ts
- src/app/project/list/my-projects-volunteer.ts
- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/common/user.service.ts
- src/app/user/edit/user-edit.component.ts
- src/app/user/list/user-list.component.ts
- src/app/user/view/user-view.component.ts
fixes #1797
update from http to httpClient
It has been done.
> update to httpClient from http #1797

- src/app/_services/email.service.ts
- src/app/_services/extfilehandler.service.ts
- src/app/_services/image-display.service.ts
- src/app/_services/image-uploader.service.ts
- src/app/about/common/developer.service.ts
- src/app/app.module.ts
- src/app/application/common/application.service.ts
- src/app/auth.service.ts
- src/app/home/home.component.ts
- src/app/organization/common/organization.service.spec.ts
- src/app/organization/common/organization.service.ts
- src/app/organization/edit/organization-edit.component.ts
- src/app/organization/view/organization-view.component.ts
- src/app/project/common/project.service.ts
- src/app/project/edit/project-edit.component.ts
- src/app/project/list/my-projects-nonprofit.ts
- src/app/project/list/my-projects-volunteer.ts
- src/app/project/list/project-list.component.ts
- src/app/project/view/project-view.component.ts
- src/app/skill/common/skill.service.ts
- src/app/user/common/user.service.ts
- src/app/user/edit/user-edit.component.ts
- src/app/user/list/user-list.component.ts
- src/app/user/view/user-view.component.ts
Reverts Code4SocialGood/c4sg-web#1822
> Revert "update to httpClient from http #1797"

- src/app/application/common/application.service.ts
fix Nothing happens when clicking "accept" for accepting a project application #1829
> fix #1829 Nothing happens when clicking "accept"
